VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "FauxClassModule"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
''
' Fake class module used for testing Project.DangerouslyImportComponentsFromSourceFolder
' and Project.ExportComponentsToSourceFolder
'
' This can be deleted after inital tests are complete.
''
Option Explicit
